//
//  ListImagesInteractorTests.swift
//  Nasa
//
//  Created by Rafael Sachetto on 20/04/19.
//  Copyright (c) 2019 Rafael Sachetto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Nasa
import XCTest

final class ListImagesInteractorTests: XCTestCase {
    // MARK: Subject under test
  
    var sut: ListImagesInteractor!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListImagesInteractor()
    }

    override func tearDown() {
        super.tearDown()
    }
  
    // MARK: Test setup
  
    func setupListImagesInteractor() {
        sut = ListImagesInteractor()
    }

    // MARK: Test doubles

    final class ListImagesPresentationLogicSpy: ListImagesPresentationLogic {
        var presentSomethingCalled = false

        func presentSomething(with response: ListImages.Something.Response) {
            presentSomethingCalled = true
        }
    }

    // MARK: Tests

    func testDoSomething() {
        // Given
        let spy = ListImagesPresentationLogicSpy()
        sut.presenter = spy
        let request = ListImages.Something.Request()

        // When
        sut.doSomething(with: request)

        // Then
        XCTAssertTrue(spy.presentSomethingCalled, "doSomething(request:) should ask the presenter to format the result")
    }
}
