//
//  ListImagesWorkerTests.swift
//  Nasa
//
//  Created by Rafael Sachetto on 20/04/19.
//  Copyright (c) 2019 Rafael Sachetto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import Nasa
import XCTest

final class ListImagesWorkerTests: XCTestCase {
    // MARK: Subject under test

    var sut: ListImagesWorker!

    // MARK: Test lifecycle

    override func setUp() {
        super.setUp()
        setupListImagesWorker()
    }

    override func tearDown() {
        super.tearDown()
    }

    // MARK: Test setup

    func setupListImagesWorker() {
        sut = ListImagesWorker()
    }

    // MARK: Test doubles

    // MARK: Tests

    func testSomething() {
        // Given

        // When

        // Then
    }
}
