//
//  ListImagesRouter.swift
//  Nasa
//
//  Created by Rafael Sachetto on 28/04/19.
//  Copyright (c) 2019 Rafael Sachetto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListImagesRoutingLogic {
    //func routeToSomewhere(segue: UIStoryboardSegue?)
}

protocol ListImagesDataPassing {
    var dataStore: ListImagesDataStore? { get }
}

final class ListImagesRouter: NSObject, ListImagesRoutingLogic, ListImagesDataPassing {
    weak var viewController: ListImagesViewController?
    var dataStore: ListImagesDataStore?

    // MARK: Routing

    //    func routeToSomewhere(segue: UIStoryboardSegue?)
    //        if let segue = segue {
    //            let destinationVC = segue.destination as! SomewhereViewController
    //            var destinationDS = destinationVC.router!.dataStore!
    //            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //        } else {
    //            let storyboard = UIStoryboard(name: "Main", bundle: nil)
    //            let destinationVC = storyboard.instantiateViewController(withIdentifier: "SomewhereViewController") as! SomewhereViewController
    //            var destinationDS = destinationVC.router!.dataStore!
    //            passDataToSomewhere(source: dataStore!, destination: &destinationDS)
    //            navigateToSomewhere(source: viewController!, destination: destinationVC)
    //        }
    //    }

    // MARK: Navigation

    //    func navigateToSomewhere(source: ListImagesViewController, destination: SomewhereViewController) {
    //        source.show(destination, sender: nil)
    //    }
    //
    //    // MARK: Passing data
    //
    //    func passDataToSomewhere(source: ListImagesDataStore, destination: inout SomewhereDataStore) {
    //        destination.name = source.name
    //    }
}
