//
//  ListImagesPresenter.swift
//  Nasa
//
//  Created by Rafael Sachetto on 28/04/19.
//  Copyright (c) 2019 Rafael Sachetto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListImagesPresentationLogic {
    func presentSegmentedControl(with response: ListImages.Cameras.Response)
}

final class ListImagesPresenter: ListImagesPresentationLogic {
    weak var viewController: ListImagesDisplayLogic?

    func presentSegmentedControl(with response: ListImages.Cameras.Response) {
        let viewModel: ListImages.Cameras.ViewModel = .init()
        viewController?.displaySegmentedControl(with: viewModel)
    }
}
