//
//  ListImagesModels.swift
//  Nasa
//
//  Created by Rafael Sachetto on 28/04/19.
//  Copyright (c) 2019 Rafael Sachetto. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListImages {
    // MARK: Use cases

    enum Cameras: String, CaseIterable {
        case curiosity
        case opportunity
        case spirit

        struct Request {
        }
        struct Response {
        }
        struct ViewModel {
            var cameras: [String] {
                return Cameras.allCases.map { camera -> String in
                    camera.rawValue.firstUppercased
                }
            }
        }
    }
}
